### ISSUE TITLE
List all sheets

### ISSUE THREAD

**Issue by gorgobacka** [PatWie/digitalmusicstand#5]
It would be nice, if there would be a way to display all available sheets.

E.g. on your demo, it's difficult so check what's available, if the user needs explicitly search for something.

**Comment by PatWie** [comment]
Isn't http://localhost:3000/sheets.json sufficient ?

**Comment by gorgobacka** [comment]
A json file is not very user friendly, specially for people without a programming background.

While looking at http://demo-digitalmusicstand.patwie.com/sheets.json, it's still not very intuitive to see what sheets are available.

**Comment by PatWie** [comment]
Ok I fixed it. And yes! This is much more usable. See latest build or demo and press "P"

**Comment by gorgobacka** [comment]
This looks great. Thank you.

**Comment by gorgobacka** [comment]
This looks great. Thank you.

But if there is only one entry left, the split of the item is a bit weird.

On your Demo instance:
![Screenshot](https://user-images.githubusercontent.com/10488441/87003868-b9984d00-c1bc-11ea-968f-56d25147ab88.png)

**Comment by PatWie** [comment]
This is fixed in the latest commit. I did not update the demo though

**Comment by gorgobacka** [comment]
Are you sure? I see it also, if I check out and run the current master branch.

**Comment by PatWie** [comment]
For me it looks like

![Bildschirmfoto vom 2020-07-13 00-08-42](https://user-images.githubusercontent.com/6756603/87257674-28b3c100-c49d-11ea-82ca-6256ae6ea6cd.png)
