### ISSUE TITLE
Improved search

### ISSUE THREAD

**Issue by gorgobacka** [PatWie/digitalmusicstand#6]
If a user want to select a Sonata from Telemann, the user would user something like "telemann sonate". But it reveals nothing.
Does the search only uses the title or the artist, but not both fields together?

And maybe a tailing space in the search input should be removed, because it doesn't add any value but reduces the results.

**Comment by PatWie** [comment]
I also noticed that. I have to look into this as I used a package for the search without looking into details yet. That's a good issue. Ideally I shouldn't care about the search.

**Comment by PatWie** [comment]
This is now fixed. Try
```
teleson
```
in
http://demo-digitalmusicstand.patwie.com/

Only the highlighting part is not working properly when a query is a mixture of artist and title

**Comment by gorgobacka** [comment]
Thanks for the fix.
