### ISSUE TITLE
How to improve the image quality?

### ISSUE THREAD

**Issue by gorgobacka** [PatWie/digitalmusicstand#7]
I'm having problems with many pdfs that the quality of the rendered images is really bad. The images are not readable. The pdf looks fine.

Here is an example (the black bar is an irregularity from the screenshot and can be ignored):
![example](https://user-images.githubusercontent.com/10488441/91646544-7afe7080-ea50-11ea-917b-e1dab22cdb50.png)

Do you have any ideas how this can be improved?

I read that the quality can be improved, if the image is rendered with a higher `scale` value and is reduced with CSS to the final size.

But I have no idea how to modify the code to archive this, because currently the `scale` depends on the height of the pdf-viewer element.

**Comment by gorgobacka** [comment]
It seems that the image in an external pdf viewer produces a grayscale image while the rendered image is only black and white. Maybe that makes the difference.

![external_viewer](https://user-images.githubusercontent.com/10488441/91646929-f6622100-ea54-11ea-80f2-f18d77c6c7a2.png)

The image sizes are nearly identical.

**Comment by PatWie** [comment]
Does https://github.com/mozilla/pdf.js/pull/10854 help?
```js
document.addEventListener('webviewerloaded', function() {
  PDFViewerApplicationOptions.set('printResolution', 300);
});
```

**Comment by gorgobacka** [comment]
That lines won't work on their own, because the event `webviewerloaded` is never set (it's done in viewer.js and you are implementing your own function to render the page)

If the solution to my problem is to increase the print resultion, I expect `printResolution` should be incorporated into `render_page`.

**Comment by PatWie** [comment]
This is still on my plate as this also bothered me on the Ipad :-)

**Comment by PatWie** [comment]
I looked into this again, but still see the issue. I might update the pdfjs dependency the coming week. :crossed_fingers:

**Comment by PatWie** [comment]
The solution is rather simple, we just need to ask pdfjs to render at a higher resolution and then down-scale it

on smaller screens

before
![2021-02-28-21-55-56_722x501](https://user-images.githubusercontent.com/6756603/109433352-30b27800-7a10-11eb-919d-881a29e4ab21.png)

after the fix
![2021-02-28-21-55-31_716x497](https://user-images.githubusercontent.com/6756603/109433359-3740ef80-7a10-11eb-8eaf-f0563facde5f.png)

This will also improve the quality on larger screens

before
![2021-02-28-22-00-34_530x180](https://user-images.githubusercontent.com/6756603/109433407-796a3100-7a10-11eb-9eef-83afe4d96310.png)
after
![2021-02-28-22-00-04_525x189](https://user-images.githubusercontent.com/6756603/109433410-7c652180-7a10-11eb-9ece-d983585d85aa.png)

**Comment by gorgobacka** [comment]
That are very great news. I will try it as soon as possible. Thanks a lot.
