### ISSUE TITLE
Specify build prerequisites

### ISSUE THREAD

**Issue by nickolay** [PatWie/digitalmusicstand#8]
Wanted to try this out. The demo wasn't loading, so I had to build myself (macOS 12.6.1; go version go1.17.3 darwin/amd64).

After following instructions in the README, I got:
```$ bash ./release.sh
./release.sh: line 6: minify: command not found
./release.sh: line 10: minify: command not found
./release.sh: line 11: minify: command not found
./release.sh: line 12: minify: command not found
./release.sh: line 13: minify: command not found
./release.sh: line 14: minify: command not found
./release.sh: line 17: /Users/nickolay/go/bin/pkger: No such file or directory
```

I guessed I needed to install:
* go get github.com/markbates/pkger/cmd/pkger (even though https://github.com/markbates/pkger says it's archived)
* https://github.com/tdewolff/minify.git (git clone + `make install`)

The version of the minify utility I got created directories instead of files for multiple input files, so I had to add the `--bundle` switch, which made me doubt my guess, but I pressed on.

The I got the following error in the browser console:
```
Uncaught SyntaxError: octal escape sequences can't be used in untagged template literals or in strict mode code [pdf.min.js:38:74993]
```

Given that it [is known to be sometimes caused by minification](https://github.com/lautis/uglifier/issues/47) I tried turning it off for pdf.js (and adjusting the <script> tags):
```
-minify -b -o static.min/js/pdf.min.js static/js/pdf.js static/js/pdf.worker.js
+cp static/js/pdf.js static/js/pdf.worker.js static.min/js/
```

After that the score was finally displayed.

Did I use the wrong (version?) of the minify utility?

**Comment by PatWie** [comment]
It might be an out-dated version as this repository is quite old.

Did you try to use the provided docker image for building?
https://github.com/PatWie/digitalmusicstand/blob/00e27034eba47f73e0cc9f60c77cbb1417a89beb/.docker/dms-release.dockerfile#L1-L7

and then

https://github.com/PatWie/digitalmusicstand/blob/00e27034eba47f73e0cc9f60c77cbb1417a89beb/.docker/Makefile#L2

**Comment by nickolay** [comment]
> Did you try to use the provided docker image for building?

No, I did not! I was too focused on the README and didn't notice the `.docker` folder:(
Indeed if I install [the correct version of minify](https://github.com/tdewolff/minify/releases/tag/v2.6.1) in addition to `go get pkger`, everything works out of the box.

A pointer like the one below would save someone like me having to figure out the dependencies by trial and error. Do you want me to make a pull-request?

> Or build it yourself:
> ```
> git clone https://github.com/PatWie/digitalmusicstand.git
> cd digitalmusicstand
> ./release.sh
> ```
> Instructions to install the required dependencies and their known-to-be-working versions are available at https://github.com/PatWie/digitalmusicstand/blob/master/.docker/dms-release.dockerfile

BTW, thanks for making this tool available!

**Comment by PatWie** [comment]
Such a PR would be indeed helpful.

**Comment by PatWie** [comment]
With goreleaser this process should now be easier.
